// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJevhsaaHdB9DTlpHvCsl4bYxGVNnXtdY',
    appId: '1:214270827161:web:fc15e8db251a1326b5b608',
    messagingSenderId: '214270827161',
    projectId: 'bwsappprod',
    authDomain: 'bwsappprod.firebaseapp.com',
    storageBucket: 'bwsappprod.appspot.com',
    measurementId: 'G-SZV9DKMQEV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxOVprO6Kks6o8WzGC4WjU6VEDSv9fO_w',
    appId: '1:214270827161:android:c356cc65ef2b46d5b5b608',
    messagingSenderId: '214270827161',
    projectId: 'bwsappprod',
    storageBucket: 'bwsappprod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0z9z3ZZERy1aizT-GYtAhulaifmlV1To',
    appId: '1:214270827161:ios:bf7bb851e23d90cab5b608',
    messagingSenderId: '214270827161',
    projectId: 'bwsappprod',
    storageBucket: 'bwsappprod.appspot.com',
    iosClientId: '214270827161-2bnfa5nkj06l718haclvef8luvne3ehv.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwsAgreementCreator',
  );
}
