// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rYy1Xt7fWeHxJtWeUiq8LNRP1pj1u0A',
    appId: '1:715847619144:web:fe826e063cdd45e9f37e7d',
    messagingSenderId: '715847619144',
    projectId: 'bwsapp-d2766',
    authDomain: 'bwsapp-d2766.firebaseapp.com',
    storageBucket: 'bwsapp-d2766.appspot.com',
    measurementId: 'G-1EVKNB5WBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzj3xspJnEhkClb0Uv3XQucgniKgux2qk',
    appId: '1:715847619144:android:7bf27e733e16ed4cf37e7d',
    messagingSenderId: '715847619144',
    projectId: 'bwsapp-d2766',
    storageBucket: 'bwsapp-d2766.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZcVtbFR8tRHxwvlljRaSZ1v3XjBj74i4',
    appId: '1:715847619144:ios:8dcc5c2022cfa4acf37e7d',
    messagingSenderId: '715847619144',
    projectId: 'bwsapp-d2766',
    storageBucket: 'bwsapp-d2766.appspot.com',
    iosBundleId: 'com.example.bwsAgreementCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZcVtbFR8tRHxwvlljRaSZ1v3XjBj74i4',
    appId: '1:715847619144:ios:8dcc5c2022cfa4acf37e7d',
    messagingSenderId: '715847619144',
    projectId: 'bwsapp-d2766',
    storageBucket: 'bwsapp-d2766.appspot.com',
    iosBundleId: 'com.example.bwsAgreementCreator',
  );
}
