// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1npWgbblhyeeWtAIfVSl1ns79V6cd7K8',
    appId: '1:898687624011:web:a56c2cd5c5d5895e313ece',
    messagingSenderId: '898687624011',
    projectId: 'bwsappdev-81e04',
    authDomain: 'bwsappdev-81e04.firebaseapp.com',
    storageBucket: 'bwsappdev-81e04.appspot.com',
    measurementId: 'G-E7BC2M32Z5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCra5j_wr2DThLVuPBKt4kucxw8Fmuf5rI',
    appId: '1:898687624011:android:b2df9223fcd52a65313ece',
    messagingSenderId: '898687624011',
    projectId: 'bwsappdev-81e04',
    storageBucket: 'bwsappdev-81e04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjdJg0vDrzaEFoDKsYMx604yU8pyMY8bI',
    appId: '1:898687624011:ios:37278f38a7147597313ece',
    messagingSenderId: '898687624011',
    projectId: 'bwsappdev-81e04',
    storageBucket: 'bwsappdev-81e04.appspot.com',
    iosClientId: '898687624011-cifdurd5prbscv6plj50nrusjj0a0oev.apps.googleusercontent.com',
    iosBundleId: 'com.example.bwsAgreementCreator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZcVtbFR8tRHxwvlljRaSZ1v3XjBj74i4',
    appId: '1:715847619144:ios:8dcc5c2022cfa4acf37e7d',
    messagingSenderId: '715847619144',
    projectId: 'bwsapp-d2766',
    storageBucket: 'bwsapp-d2766.appspot.com',
    iosBundleId: 'com.example.bwsAgreementCreator',
  );
}